---
language: ruby
sudo: false
cache: bundler
rvm:
- 2.6.3
script: bundle exec rake $TASK
env:
- TASK='default'
- TASK='jekyll:check_external_links'
- TASK='spellcheck'
matrix:
  fast_finish: true
  allow_failures:
  - env: TASK='jekyll:check_external_links'
  - env: TASK='spellcheck'
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
